version: "3"
services:
  mongodb:
    container_name: mongodb_demo
    image: uwitech/mongodb
    volumes:
      - mongodb-data:/data/db
  dhis-db:
    container_name: fr-db_demo
    image: uwitech/postgresql
    env_file: .env
    volumes:
      - fr-pgdata:/var/lib/postgresql/data
  openempi-db:
    container_name: openempi-db_demo
    image: uwitech/postgresql
    volumes:
      - cr-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openempi
      - POSTGRES_DB=openempi
      - POSTGRES_PASSWORD=openempi
  postgresql-openxds:
    container_name: postgresql-openxds
    image: uwitech/postgresql
    volumes:
      - openxds-pgdata:/var/lib/postgresql/data
  openmrs-mysql-db:
    container_name: openmrs-mysql-db
    image: uwitech/mysql
    command: --sql_mode="NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    env_file: .env
    volumes:
      - openmrs-mysqldata:/var/lib/mysql

  ohie-il:
    depends_on:
      - mongodb
    env_file: .env
    container_name: ohie-il_demo
    image: uwitech/ohie-il
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5012:5012"
      - "8989:8989"
      - "8500:8500"
    volumes:
      - /etc/ssl/crt:/var/openhim/crt
  ohie-il-console:
    container_name: ohie-il-console_demo
    env_file: .env
    image: uwitech/ohie-il-console
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/crt:/etc/nginx/certs
  ohie-ilr:
    container_name: ohie-ilr-demo
    env_file: .env
    image: uwitech/ohie-ilr
    volumes:
      - openinfoman-data:/var/lib/openinfoman/data
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "1"

  ohie-fr:
    container_name: ohie-fr-demo
    env_file: .env
    image: uwitech/ohie-fr
    depends_on:
      - dhis-db
  ohie-cr:
    container_name: ohie-cr-demo
    env_file: .env
    image: uwitech/ohie-cr
    ports:
      - "5667:5666"
    volumes:
      - cr-orientdata:/data
    depends_on:
      - openempi-db

  openxds:
    image: uwitech/openxds
    container_name: openxds-demo
    depends_on:
      - postgresql-openxds

  openshr:
    container_name: oshr-demo
    image: uwitech/oshr
    env_file: .env
    depends_on:
      - openmrs-mysql-db
      - openxds
    volumes:
      - shr-orientdata:/root/.OpenMRS/

  nginx-proxy:
    container_name: nginx-proxy-demo
    build: nginx-proxy
    env_file: .env
    ports:
      - "9000:9000"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - ohie-fr
      - ohie-cr
      - openshr
    volumes:
      - /etc/ssl/crt:/etc/nginx/certs

  etl:
    container_name: ohie-etl-demo
    image: uwitech/etl
    env_file: .env
    depends_on:
      - openmrs-mysql-db

volumes:
  mongodb-data:
  fr-pgdata:
  cr-pgdata:
  cr-orientdata:
  openxds-pgdata:
  openmrs-mysqldata:
  shr-orientdata:
  openinfoman-data:
